// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyA0pniGPprx9ef4PbJRYHGg2eis81TYsG8",
      authDomain: "dedeowner-a6cbd.firebaseapp.com",
      projectId: "dedeowner-a6cbd",
      storageBucket: "dedeowner-a6cbd.appspot.com",
      messagingSenderId: "662224915108",
      appId: "1:662224915108:web:9e4afad13b509d6f263431",
      measurementId: "G-YM2783BYJR");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7aU_83jx-OxcRuNJTxHpuQMfbmZdxauM',
    appId: '1:690847738696:android:e6485a2251913e7651217d',
    messagingSenderId: '690847738696',
    projectId: 'dedeowner-7baee',
    storageBucket: 'dedeowner-7baee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXwbn9f7Z_UPQ7Sqv9DUjNe6kZhlFx3l4',
    appId: '1:690847738696:ios:d358c3c655e84c7051217d',
    messagingSenderId: '690847738696',
    projectId: 'dedeowner-7baee',
    storageBucket: 'dedeowner-7baee.appspot.com',
    iosClientId: '690847738696-4tgu60e64ve8fn953rlsg4dvnd50kpkq.apps.googleusercontent.com',
    iosBundleId: 'com.smlsoft.dedeowner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXwbn9f7Z_UPQ7Sqv9DUjNe6kZhlFx3l4',
    appId: '1:690847738696:ios:c41554236b3f309451217d',
    messagingSenderId: '690847738696',
    projectId: 'dedeowner-7baee',
    storageBucket: 'dedeowner-7baee.appspot.com',
    iosClientId: '690847738696-p982e8st16o43tgu04p56b1vaadldbln.apps.googleusercontent.com',
    iosBundleId: 'com.smlsoft.dedeowner.RunnerTests',
  );
}
